[visualization]
export = true
interval = 7200

[[visualize_agent]]
name = "TumorCell"
additional_data_members = ["diameter_","volume_", "type_"]

[[visualize_agent]]
name = "CartCell"
additional_data_members = ["diameter_","volume_"]
