[visualization]
export = true
interval = 7200

[[visualize_agent]]
name = "TumorCell"
additional_data_members = [
	{name = "diameter_", function = "diameter_"},
	{name = "volume_", function = "volume_"},
	{name = "cell_type", function = "GetTypeAsInt"}
]

[[visualize_diffusion]]
name = "oxygen"
