name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubu22-gcc
            os: ubuntu-22.04
            compiler: gcc

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          #sudo apt-get update
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y gcc g++ cmake make
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          else
            sudo apt-get install -y clang cmake make
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi

      - name: Cache pyenv
        uses: actions/cache@v4
        id: pyenv-cache
        with:
          path: ~/.pyenv
          key: ${{ matrix.os }}-pyenv-3.9.1

      - name: Install pyenv dependency
        if: steps.pyenv-cache.outputs.cache-hit != 'true'
        run: |
          if [ ! -f ".pyenv/bin/pyenv" ]; then
            curl https://pyenv.run | bash
          fi
          export PATH=".pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          if [ ! -f  ".pyenv/versions/3.9.1/lib/libpython3.so" ]; then
            PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.9.1
          fi
          pyenv shell 3.9.1

      - name: Cache Third Party Packages
        uses: actions/cache@v4
        with:
          path: build/third_party
          key: ${{ matrix.os }}-third-party-${{ hashFiles('cmake/external/SHA256Digests.cmake') }}

      - name: Restore BDM Cache
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            biodynamo
          key: ${{ matrix.os }}-bdm

      - name: Build BDM if Cache is not found
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          export PATH=".pyenv/bin:$PATH"
          #eval "$(pyenv init --path)"
          #eval "$(pyenv init -)"
          pyenv shell 3.9.1
          python --version
          git clone --depth=1 https://github.com/BioDynaMo/biodynamo.git
          cd biodynamo
          cmake \
             -Dnotebooks=OFF \
             -Dparaview=ON \
             -Dbenchmark=ON \
             -Dlibgit2=ON \
             -Dsbml=OFF \
             -DCMAKE_BUILD_TYPE=Release \
             -B build
          cmake --build build --config Release
          cd ..
      - name: Save Cache BDM
        uses: actions/cache/save@v4
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          path: |
            biodynamo-*
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Configure project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cmake --build build -- -j$(nproc)

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure

      - name: Setup tmate session
        if: ${{ !cancelled() && runner.debug }}
        uses: mxschmitt/action-tmate@v3
        # When debugging increase to a suitable value!
        timeout-minutes: 30
